### ISSUE TITLE
Error since latest version 1.4.6

### ISSUE THREAD

**Issue by MilesTEG1** [marvinroger/hass-addon-tiko#14]
Hello
since the latest version 1.4.6, the addon doesn't work anymore, and show this error:

```log
                      "message": "Invalid literal value, expected false"
                    }
                  ],
                  "name": "ZodError"
                },
                {
                  "issues": [
                    {
                      "code": "invalid_type",
                      "expected": "string",
                      "received": "boolean",
                      "path": [
                        "data",
                        "properties",
                        0,
                        "rooms",
                        4,
                        "status",
                        "sensorDisconnected"
                      ],
                      "message": "Expected string, received boolean"
                    }
                  ],
                  "name": "ZodError"
                }
              ],
              "path": [
                "data",
                "properties",
                0,
                "rooms",
                4,
                "status",
                "sensorDisconnected"
              ],
              "message": "Invalid input"
            },
            {
              "code": "invalid_union",
              "unionErrors": [
                {
                  "issues": [
                    {
                      "received": true,
                      "code": "invalid_literal",
                      "expected": false,
                      "path": [
                        "data",
                        "properties",
                        0,
                        "rooms",
                        5,
                        "status",
                        "sensorDisconnected"
                      ],
                      "message": "Invalid literal value, expected false"
                    }
                  ],
                  "name": "ZodError"
                },
                {
                  "issues": [
                    {
                      "code": "invalid_type",
                      "expected": "string",
                      "received": "boolean",
                      "path": [
                        "data",
                        "properties",
                        0,
                        "rooms",
                        5,
                        "status",
                        "sensorDisconnected"
                      ],
                      "message": "Expected string, received boolean"
                    }
                  ],
                  "name": "ZodError"
                }
              ],
              "path": [
                "data",
                "properties",
                0,
                "rooms",
                5,
                "status",
                "sensorDisconnected"
              ],
              "message": "Invalid input"
            }
          ]
              at get error [as error] (file:///app/node_modules/zod/lib/index.mjs:538:31)
              at validate (file:///app/dist/lib/validation.js:8:36)
              at doTikoRequest (file:///app/dist/tiko/client.js:167:28)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async TikoClient.fetchData (file:///app/dist/tiko/client.js:58:32)
              at async file:///app/dist/index.js:16:27
    ```

Is there a way you can fix this @marvinroger ?
Thanks in advance :)

**Comment by marvinroger** [comment]
Hmm, looks like the API can be inconsistent depending on hardware used. The 1.4.7 should fix the issue!

**Comment by MilesTEG1** [comment]
Great 👍🏻 
Hope the 1.47 is comming soon, the temperature in Normandie aren't not too warm today 😉

**Comment by marvinroger** [comment]
It's already deployed!

**Comment by MilesTEG1** [comment]
Thank you.
It's working again :D

**Comment by MilesTEG1** [comment]
Can close this issue ;)
