### ISSUE TITLE
« Current temperature » « expected number » « received : null »

### ISSUE THREAD

**Issue by SeeeeebDe** [marvinroger/hass-addon-tiko#9]
Hello!

J’ouvre un fil dédié pour un souci que je rencontre depuis le début et qui empêche le démarrage de l’addon.

Après les quelques derniers échanges sur le sujet dans un autre fil… il en ressort que c’est un souci particulier que j’ai, mais aussi je n’avais pas noté ça jusqu’ici, mais le souci semble lié à une température qui remonte mal.

‘du coup avec ce dernier constat je viens de me dire qu’il y avait peut être un lien avec le fait qu’un des radiateurs et son boîtier… sont débranchés ! (Pour cause de travaux).

Si c’est lié, alors il manquerait un gestion d’appareil ne répondant plus 😌

je vais voir pour rebrancher le boîtier sur une prise pour faire un essai et je vous tiens au courant.

[19:17:02] INFO: Running in Home Assistant mode
[19:17:05.813] ERROR (7): Unable to fetch initial data from tiko API
    err: {
      "type": "Error",
      "message": "The data from tiko was not the expected shape: Validation error: Expected number, received null at \"data.properties[0].rooms[5].currentTemperatureDegrees\": [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"number\",\n    \"received\": \"null\",\n    \"path\": [\n      \"data\",\n      \"properties\",\n      0,\n      \"rooms\",\n      5,\n      \"currentTemperatureDegrees\"\n    ],\n    \"message\": \"Expected number, received null\"\n  }\n]",
      "stack":
          Error: The data from tiko was not the expected shape
              at doTikoRequest (file:///app/dist/tiko/client.js:168:24)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async TikoClient.fetchData (file:///app/dist/tiko/client.js:57:32)
              at async file:///app/dist/index.js:16:27
          caused by: ZodValidationError: Validation error: Expected number, received null at "data.properties[0].rooms[5].currentTemperatureDegrees"
              at fromZodError (file:///app/node_modules/zod-validation-error/dist/index.mjs:169:10)
              at validate (file:///app/dist/lib/validation.js:8:16)
              at doTikoRequest (file:///app/dist/tiko/client.js:166:28)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async TikoClient.fetchData (file:///app/dist/tiko/client.js:57:32)
              at async file:///app/dist/index.js:16:27
          caused by: ZodError: [
            {
              "code": "invalid_type",
              "expected": "number",
              "received": "null",
              "path": [
                "data",
                "properties",
                0,
                "rooms",
                5,
                "currentTemperatureDegrees"
              ],
              "message": "Expected number, received null"
            }
          ]
              at get error [as error] (file:///app/node_modules/zod/lib/index.mjs:538:31)
              at validate (file:///app/dist/lib/validation.js:8:36)
              at doTikoRequest (file:///app/dist/tiko/client.js:166:28)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async TikoClient.fetchData (file:///app/dist/tiko/client.js:57:32)
              at async file:///app/dist/index.js:16:27
    }

**Comment by SeeeeebDe** [comment]
Je m’auto répond : 
Et bien c’était ça !
Boîtier rebranché, et la ça marche directement !

(après avoir corrigé mon url mqtt, j’avais juste saisi l’ip 192.168.xxx.xxx:1883 , et il manquait mqtt:// devant pour que ça fonctionne)

Bon et bien du coup merci pour tout ce super boulot !
Et merci pour m’avoir aidé à avoir le déclic sur l’origine du souci ☺️

Pette suggestion d’amélioration du coup : si une température remonte « null », ignorer le radiateur et juste remonter un statut d’indisponibilité 🤓

**Comment by marvinroger** [comment]
Je vais essayer de couper les miens et voir si j'arrive à reproduire, merci pour l'info et le diagnostic !

**Comment by marvinroger** [comment]
Hello !
C'est corrigé dans la 1.4.5, merci de ton aide 😉
